# iOS CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/ios-migrating-from-1-2/ for more details
#
version: 2
jobs:
  build-and-test:

    # Specify the Xcode version to use
    macos:
      xcode: "9.2.0"

    steps:
      - checkout
      - run: bundle install
      # Install CocoaPods
      - run:
          name: Install CocoaPods
          command: bundle exec pod install

      # Build the app and run tests
      - run:
          name: Build and run tests
          command: bundle exec fastlane scan

      # Collect XML test results data to show in the UI,
      # and save the same XML files under test-results folder
      # in the Artifacts tab
      - store_test_results:
          path: test_output/report.xml
      - store_artifacts:
          path: /tmp/test-results
          destination: scan-test-results
      - store_artifacts:
          path: ~/Library/Logs/scan
          destination: scan-logs

  alpha:
    # Specify the Xcode version to use
    macos:
      xcode: "9.2.0"

    steps:
      - checkout
      - run: bundle install
      
      # Install CocoaPods
      - run:
          name: Install CocoaPods
          command: bundle exec pod install

      # Build the app and run tests
      - run:
          name: Build and distribute Alpha
          command: bundle exec fastlane alpha

workflows:
  version: 2
  build-and-test:
    jobs:
      - build-and-test
      - alpha:
          filters:
            branches:
              only: develop
          requires:
            - build-and-test
